# Generated by Django 4.1.7 on 2023-04-05 16:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AttorneysApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardInformations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "details",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("awardimg", models.ImageField(blank=True, upload_to="attoneysaward/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttorneysProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, upload_to="attoneys/")),
                ("associate_at", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("biography", ckeditor_uploader.fields.RichTextUploadingField()),
                ("contact", ckeditor_uploader.fields.RichTextUploadingField()),
                ("universityattended", models.CharField(blank=True, max_length=15)),
                ("lawscholattended", models.CharField(blank=True, max_length=15)),
                ("yearoffirstadmission", models.CharField(blank=True, max_length=50)),
                ("admission", models.CharField(blank=True, max_length=50)),
                ("membership", models.CharField(blank=True, max_length=50)),
                ("birthinformation", models.CharField(blank=True, max_length=10)),
                ("isln", models.CharField(blank=True, max_length=5)),
                ("facebook", models.CharField(blank=True, max_length=50)),
                ("instagram", models.CharField(blank=True, max_length=50)),
                ("twitter", models.CharField(blank=True, max_length=50)),
                ("youtube", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "award",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AttorneysApp.awardinformations",
                    ),
                ),
                (
                    "practisearea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AttorneysApp.areaofpractise",
                    ),
                ),
            ],
        ),
    ]
