# Generated by Django 4.1.7 on 2023-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AttorneysApp", "0002_awardinformations_attorneysprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="attorneysprofile",
            name="primary_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
