# Generated by Django 4.2 on 2023-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIPI_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeechAudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "audiofile",
                    models.FileField(null=True, upload_to="audio/", verbose_name=""),
                ),
            ],
        ),
    ]
