# Generated by Django 4.2 on 2023-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIPI_App", "0003_nudityimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "image",
                    models.FileField(
                        null=True, upload_to="weaponsimgs/", verbose_name=""
                    ),
                ),
            ],
        ),
    ]
