# Generated by Django 4.2 on 2023-07-11 16:02

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("AIPI_App", "0005_weaponsvideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbededItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
